use ::std::path::PathBuf;

const TEST_ZSHRC: &str = "# Test zshrc -- autogenerated by build.rs
emulate -L zsh
# stty sane

typeset -a targets
targets=(\"$PWD/target/\"{debug,release}/lib*.so(*:a))

typeset -i mp=$#targets
if ((mp == 0)); then
    echo 'Failed to find target binaries!'
else
    if ((mp != 1)); then
        if [[ $targets[2] -nt $targets[1] ]]; then
            mp=2
        else
            mp=1
        fi
    fi

    module_path+=(\"${targets[mp]:h}\")
    targets[1]=\"${${targets[mp]:t:r}#libbb}\"

    print -l 'Now run the command:' \"zmodload \\${targets[1]}\"
    zmodload \"${targets[1]}\"
fi

# unset targets mp
";

fn main() -> std::io::Result<()> {
    let manifest: PathBuf = std::env::var_os("CARGO_MANIFEST_DIR").unwrap().into();
    let zdotdir = manifest.join("gitignored/zdotdir");

    std::fs::create_dir_all(&zdotdir)?;
    std::fs::write(zdotdir.join(".zshrc"), TEST_ZSHRC)?;
    println!("cargo::warning=To test the module, run `ZDOTDIR={zdotdir:?} =zsh`");
    Ok(())
}
