# Test zshrc -- autogenerated by build.rs
emulate -L zsh
# stty sane
setopt nullglob

typeset -a targets
targets=("$PWD/target/"{debug,release}/lib*.so(*:a))

typeset -i mp=$#targets
if ((mp == 0)); then
    echo 'Failed to find target binaries!'
else
    if ((mp != 1)); then
        if [[ $targets[2] -nt $targets[1] ]]; then
            mp=2
        else
            mp=1
        fi
    fi

    module_path+=("${targets[mp]:h}")
    targets[1]="${${targets[mp]:t:r}#libbb}"

    print -l 'Now running the command:' "zmodload ${targets[1]}" ''
    zmodload "${targets[1]}"

    print -l '[0m' 'Exiting in 3 seconds...'
    sleep 3
    exit 0
fi

# unset targets mp
